services:
  coordinated-time-bot:
    build:
      # context: https://github.com/odd-paritybit/eve-time-bot.git
      dockerfile: Dockerfile
    environment:
      DISCORD_TOKEN: bot-token-goes-here
      ASPNETCORE_URLS: http://0.0.0.0:8080
    ports:
      - 8080:8080
    volumes:
      - coordinated-time-bot-data:/app

volumes:
  coordinated-time-bot-data:
